spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/testtodos?useUnicode=true&characterEncoding=utf8&authenticationPlugins=mysql_native_password
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: testtodos
        show_sql: true            # 콘솔에 SQL 쿼리 출력
        use_sql_comments: true    # SQL에 주석 추가
        format_sql: true          # SQL 출력 포맷 예쁘게
        default_batch_fetch_size: 100  # N+1 문제 완화용 배치 크기

jwt:
  secret: 2dGcYFpHZK2aOCvMjwDdxf8QG6E0uNzU7PX51Fh2ZTg=
